### ISSUE TITLE
Set token-endpoint-auth-method

### ISSUE THREAD

**Issue by marcelogamba** [Improwised/hydra-webui#20]
Hi there,

First I'd like to congratulate for the project. It's still very young but can help lots of people to get started with OryHydra more easily
 
Secondly It would be nice to be able to set "token-endpoint-auth-method". Current version doesn't support it and register clients with default value "client_secret_basic"

Thanks and good coding

**Comment by deltasquare4** [comment]
Thanks for the kind words. We'll look into it.

**Comment by ekta-kakadia** [comment]
https://user-images.githubusercontent.com/22571041/134321432-1e9b7687-13d3-4908-85c0-22a32e898924.mp4

**Comment by deltasquare4** [comment]
@marcelogamba Please take it for a spin and let me know how it goes. Thanks for your inputs in making the project better.
