### ISSUE TITLE
Create Client in Hydra-webui

### ISSUE THREAD

**Issue by Luv7804** [Improwised/hydra-webui#41]
- Run hydra-webui
- Goto http://127.0.0.1:3000
- Create Client should work

**Comment by munir131** [comment]
@Luv7804 What are you getting? Is there any error?

**Comment by Luv7804** [comment]
504 Gateway Timeout

**Comment by Luv7804** [comment]
quick setup of Ory Hydra
https://www.ory.sh/docs/hydra/5min-tutorial
